{% set name = "auto-changelog" %}
{% set version = "1.2.2" %}
{% set sha256 = "30ce8a0ba22238afbbd52cd9c482d84a18513f771ec4cdfa9d7e4ed6bc566d19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CookPete/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: npm install -g auto-changelog@{{ version }}

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  requires:
    - nodejs
  commands:
    - npm list -g {{ name }}
    - auto-changelog --version
    - '[[ -z $(find $PREFIX/lib/node_modules -name binding.gyp) ]]'  # [unix]

about:
  home: https://github.com/CookPete/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Command line tool for generating a changelog from git tags and commit history.'
  description: |
    Command line tool for generating a changelog from git tags and commit history.
  doc_url: https://github.com/CookPete/auto-changelog
  dev_url: https://github.com/CookPete/auto-changelog

extra:
  recipe-maintainers:
    - jeffkpayne
